"""Auto-generated models for Headline Recommendations from Amazon Ads API v0."""

from __future__ import annotations

from typing import Literal

from pydantic import Field

from ads_api.models._core.base import LenientModel, StrictModel


class RecommendedHeadline(LenientModel):
    """Recommended Headline in response object. Recommended headline will be locale specific, i.e. for an asin input in ES, Recommended headline will be in ES."""

    headlineId: str | None = Field(default=None, description="Unique Id of Recommended headline.")
    headline: str | None = Field(default=None, max_length=50, description="String that contains Recommended headline.")


class SDHeadlineRecommendationRequest(StrictModel):
    """Request structure of SD headline recommendation API."""

    asins: list[str] | None = Field(
        default=None, min_length=1, max_length=100, description="An array of ASINs associated with the creative."
    )
    maxNumRecommendations: float | None = Field(
        default=None,
        ge=1,
        le=10,
        description="Maximum number of recommendations that API should return. Response will [0, maxNumRecommendations] recommendations (recommendations are not guaranteed as there can be instances where the ML model can not generate policy compliant headlines for the given set of asins).",
    )
    adFormat: Literal["SPONSORED_DISPLAY"] | None = Field(default=None)


class SDHeadlineRecommendationResponse(LenientModel):
    """Response structure of SD headline recommendation API."""

    requestId: str | None = Field(
        default=None, description="An identifier for request made which is generated by server."
    )
    recommendations: list[RecommendedHeadline] | None = Field(
        default=None,
        min_length=1,
        max_length=10,
        description="Recommendations are sorted, i.e., more suitable headline has lesser array index value.",
    )


__all__ = ["RecommendedHeadline", "SDHeadlineRecommendationRequest", "SDHeadlineRecommendationResponse"]
