"""Auto-generated models for Recommendations from Amazon Ads API v0."""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import Field

from ads_api.models._core.base import LenientModel, StrictModel
from ads_api.models._core.lenient_enum import lenient_enum
from ads_api.models.v0._shared import (
    LandingPage,
    LandingPageType,
    SBTargetingBrand,
)


class CostControlMetric(StrEnum):
    """
    Cost control metric to retrieve recommended value for.  Currently only COST_PER_CLICK is supported.
    """

    COST_PER_CLICK = "COST_PER_CLICK"


class BudgetRecommendation(LenientModel):
    """Budget recomendation for campagins."""

    campaignId: str = Field(description="The identifier of a campaign.")
    suggestedBudget: float = Field(description="Recommended budget for the campaign.")
    index: float = Field(description="Correlate the recommendation to the campaign index in the request. Zero-based.")
    sevenDaysMissedOpportunities: SevenDaysMissedOpportunities


class BudgetRecommendationErrorResult(LenientModel):
    """Error that occurred when generating budget recommendations."""

    code: str = Field(description="A human-readable description of the enumerated response code in the `code` field.")
    campaignId: str = Field(description="The identifier of a campaign.")
    index: float = Field(description="Correlate the recommendation to the campaign index in the request. Zero-based.")
    details: str = Field(description="An enumerated response code.")


class GetBudgetRecommendationsRequestContent(StrictModel):
    campaignIds: list[str] = Field(min_length=1, max_length=100, description="List of CampaignIds")


class GetBudgetRecommendationsResponseContent(LenientModel):
    success: list[BudgetRecommendation] = Field(
        min_length=0, max_length=100, description="List of successful budget recommendations for campaigns."
    )
    error: list[BudgetRecommendationErrorResult] = Field(
        min_length=0, max_length=100, description="List of errors that occurred when generating budget recommendations."
    )


class HeadlineSuggestionRequest(StrictModel):
    """Request structure of headline suggestion API."""

    asins: list[str] | None = Field(
        default=None,
        min_length=1,
        max_length=3,
        description="An array of ASINs associated with the creative. Note do not pass an empty array, this results in an error.",
    )
    storePages: list[StorePage] | None = Field(
        default=None,
        min_length=1,
        max_length=3,
        description="An array of Store Pages associated with SB Spotlight Creative.",
    )
    maxNumSuggestions: float | None = Field(
        default=None,
        ge=1,
        le=10,
        description="Maximum number of suggestions that API should return. Response will [0, maxNumSuggestions] suggestions (suggestions are not guaranteed).",
    )
    adFormat: str | None = Field(default=None)


class HeadlineSuggestionResponse(LenientModel):
    """Response structure of headline suggestion API."""

    requestId: str | None = Field(
        default=None, description="An identifier for request made which is generated by server."
    )
    suggestions: list[SuggestedHeadline] | None = Field(
        default=None, description="Suggestions are sorted, i.e., more suitable headline has lesser array index value"
    )


class SBOptimizationRecommendationRequestContent(StrictModel):
    costControlMetric: Annotated[CostControlMetric, lenient_enum(CostControlMetric)]
    landingPages: list[LandingPage] = Field(min_length=1, max_length=10)


class SBOptimizationRecommendationResponseContent(LenientModel):
    minimumValue: float = Field(description="Minimum accepted value for cost control metric.")
    costControlMetric: Annotated[CostControlMetric | str, lenient_enum(CostControlMetric)]
    recommendedValue: float = Field(description="Recommended value for cost control metric.")


class SBTargetingGetNegativeBrandsResponseContent(LenientModel):
    """Response object for /sb/negativeTargets/brands/recommendations containing list of brands for negative targeting."""

    brands: list[SBTargetingBrand] | None = Field(default=None, max_length=100, description="List of Brands.")
    nextToken: str | None = Field(
        default=None,
        description="Operations that return paginated results include a pagination token in this field. To retrieve the next page of results, call the same operation and specify this token in the request. If the `NextToken` field is empty, there are no further results.",
    )


class SevenDaysMissedOpportunities(LenientModel):
    """Missed Opportunities in the trailing seven days."""

    estimatedMissedSalesLower: float | None = Field(
        default=None, description="Lower bound of the estimated Missed Sales. This will be in local currency."
    )
    estimatedMissedSalesUpper: float | None = Field(
        default=None, description="Upper bound of the estimated Missed Sales. This will be in local currency."
    )
    endDate: str | None = Field(
        default=None,
        pattern="^20[1-9][0-9]-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$",
        description="End date of the Missed Opportunities date range (YYYY-MM-DD) in local time.",
    )
    estimatedMissedImpressionsLower: float | None = Field(
        default=None, description="Lower bound of the estimated Missed Impressions."
    )
    estimatedMissedClicksLower: float | None = Field(
        default=None, description="Lower bound of the estimated Missed Clicks."
    )
    estimatedMissedClicksUpper: float | None = Field(
        default=None, description="Upper bound of the estimated Missed Clicks."
    )
    estimatedMissedImpressionsUpper: float | None = Field(
        default=None, description="Upper bound of the estimated Missed Impressions."
    )
    startDate: str | None = Field(
        default=None,
        pattern="^20[1-9][0-9]-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$",
        description="Start date of the Missed Opportunities date range (YYYY-MM-DD) in local time.",
    )
    percentTimeInBudget: float | None = Field(
        default=None, description="Percentage of time the campaign is active with a budget."
    )


class StorePage(StrictModel):
    displayName: str | None = Field(
        default=None, description="Display Name of the store page shown on a store spotlight campaign."
    )
    primaryAsin: str | None = Field(
        default=None,
        description="Selected asin from the store page which is displayed on the store spotlight campaign.",
    )


class SuggestedHeadline(LenientModel):
    """Suggested Headline in response object."""

    headlineId: str | None = Field(default=None, description="Unique Id of suggested headline.")
    headline: str | None = Field(default=None, description="String that contains suggested headline.")


__all__ = [
    "BudgetRecommendation",
    "BudgetRecommendationErrorResult",
    "CostControlMetric",
    "GetBudgetRecommendationsRequestContent",
    "GetBudgetRecommendationsResponseContent",
    "HeadlineSuggestionRequest",
    "HeadlineSuggestionResponse",
    "LandingPage",
    "LandingPageType",
    "SBOptimizationRecommendationRequestContent",
    "SBOptimizationRecommendationResponseContent",
    "SBTargetingBrand",
    "SBTargetingGetNegativeBrandsResponseContent",
    "SevenDaysMissedOpportunities",
    "StorePage",
    "SuggestedHeadline",
]
